 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.31.4.158:5000
Press CTRL+C to quit
61.73.4.238 - - [12/Nov/2023 05:01:16] "POST /font/upload HTTP/1.1" 200 -
[2023-11-12 05:01:46,278] ERROR in app: Exception on /font/combine [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 34, in combine
    jamo2.run()
  File "/home/ubuntu/yourwriting-font-server/jamo2.py", line 191, in run
    combine_letters_3()
  File "/home/ubuntu/yourwriting-font-server/jamo2.py", line 78, in combine_letters_3
    consonant2 = Image.open('./crops/' + str(k) + '.PNG')
  File "/home/ubuntu/.local/lib/python3.8/site-packages/PIL/Image.py", line 3305, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file './crops/6.PNG'
61.73.4.238 - - [12/Nov/2023 05:01:46] "GET /font/combine HTTP/1.1" 500 -
[2023-11-12 05:02:01,068] ERROR in app: Exception on /font/combine [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 34, in combine
    jamo2.run()
  File "/home/ubuntu/yourwriting-font-server/jamo2.py", line 191, in run
    combine_letters_3()
  File "/home/ubuntu/yourwriting-font-server/jamo2.py", line 77, in combine_letters_3
    vowel = Image.open('./crops/' + str(j) + '.PNG')
  File "/home/ubuntu/.local/lib/python3.8/site-packages/PIL/Image.py", line 3305, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file './crops/32.PNG'
61.73.4.238 - - [12/Nov/2023 05:02:01] "GET /font/combine HTTP/1.1" 500 -
[2023-11-12 05:02:07,447] ERROR in app: Exception on /font/combine [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 34, in combine
    jamo2.run()
  File "/home/ubuntu/yourwriting-font-server/jamo2.py", line 189, in run
    combine_letters_1()
  File "/home/ubuntu/yourwriting-font-server/jamo2.py", line 34, in combine_letters_1
    consonant2 = Image.open('./crops/' + str(k) + '.PNG')  # 받침
  File "/home/ubuntu/.local/lib/python3.8/site-packages/PIL/Image.py", line 3305, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file './crops/15.PNG'
61.73.4.238 - - [12/Nov/2023 05:02:07] "GET /font/combine HTTP/1.1" 500 -
61.73.4.238 - - [12/Nov/2023 05:04:41] "GET /font/combine HTTP/1.1" 200 -
